name: Code Coverage & Mutation Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore server/api/api.csproj

      - name: Install Required tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: SonarQube begin analysis
        run: |
          dotnet sonarscanner begin \
            /k:"VICJEN-Filmjournal" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.qualitygate.timeout=300

      - name: Build
        run: dotnet build server/api/api.csproj

      - name: Run tests with code coverage
        run: dotnet test server/Tests/Tests.csproj --collect:"XPlat Code Coverage" --results-directory server/TestResults

      - name: Generate report
        run: reportgenerator -reports:"server/TestResults/**/coverage.cobertura.xml" -targetdir:coverage-report -reporttypes:SonarQube
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage-report/
          retention-days: 30

      - name: Run Stryker
        run: cd server && dotnet stryker --break-at 80

      - name: SonarQube end analysis (quality gate)
        run: |
          dotnet sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
      - name: Application Version
        id: semver-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          
      
      - name: Display Version
        run: echo "Generated version is ${{ steps.semver-app.outputs.version }}"
      
      
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: Build and push Docker image
        run: | 
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build \
          -t ghcr.io/${REPO_LOWER}:staging \
          -t ghcr.io/${REPO_LOWER}:${{ steps.semver-app.outputs.version }} \
          -f server/Dockerfile \
          server
          docker push ghcr.io/${REPO_LOWER} --all-tags
          
      - name: Create Release Notes
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=${REPO_LOWER}" >> $GITHUB_ENV
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          allowUpdates: true
          body: |
            This release includes the following container image:
            http://ghcr.io/${{ env.REPO_LOWER }}:${{ steps.semver-app.outputs.version }}
            
      - name: Deliver Docker Compose file to staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "server/docker-compose.yaml"
          target: dowa/
          strip_components: 1
          
      - name: Run Docker Compose on staging server
        uses: appleboy/ssh-action@v1.2.1
        with: 
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            docker compose pull
            docker compose up -d